feature: mail modal

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,9 +1,9 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-# branch="$(git rev-parse --abbrev-ref HEAD)"
+branch="$(git rev-parse --abbrev-ref HEAD)"
 
-# if [ "$branch" = "develop" ]; then
-#   echo "You can't commit directly to develop branch"
-#   exit 1
-# fi
+if [ "$branch" = "develop" ]; then
+  echo "You can't commit directly to develop branch"
+  exit 1
+fi
